# Generated by Django 5.2.4 on 2025-07-29 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moneyout',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
